import Head from 'next/head'
import dynamic from 'next/dynamic'
import PropTypes from 'prop-types'

const Header = dynamic(() => import('@shared/components/header'))
const Footer = dynamic(() => import('@shared/components/footer'))

function AppLayout({ children }) {
  return (
    <>
      <Head>
        <title>BioFinder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      {children}
      <Footer />
    </>
  )
}
AppLayout.propTypes = {
  children: PropTypes.node.isRequired
}
export default AppLayout